<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <EmbeddedResource Include="Migrations\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\contracts\api\AuditFlow.Contracts.Api\AuditFlow.Contracts.Api.csproj" />
    <ProjectReference Include="..\..\..\contracts\events\AuditFlow.Contracts.Events\AuditFlow.Contracts.Events.csproj" />
    <ProjectReference Include="..\..\building-blocks\AuditFlow.BuildingBlocks\AuditFlow.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
